import { sanitizeStateName } from "./reserved.ts";

export type AssembledParts = {
  globals: string[];
  functions: string[];
  /** state name → event handler source (already includes signature + braces) */
  states: Record<string, string[]>;
  notes?: string[];
};

function indentBlock(src: string, spaces = 4): string {
  const pad = " ".repeat(spaces);
  return src
    .replace(/\s+$/g, "")
    .split("\n")
    .map((line) => (line.length ? pad + line : line))
    .join("\n");
}

function formatState(name: string, events: string[], isDefault: boolean): string {
  const header = isDefault ? "default" : `state ${name}`;
  const cleaned = events.map((e) => e.trim()).filter(Boolean);
  const body = cleaned.length
    ? cleaned.map((e) => indentBlock(e, 4)).join("\n\n")
    : indentBlock(
        "state_entry()\n{\n    // default must exist and come first. Snap an event brick here.\n}",
        4,
      );
  return `${header}\n{\n${body}\n}`;
}

/**
 * Assemble a legal LSL compilation unit:
 * comments, globals, user functions, then default state, then other states.
 */
export function assembleScript(parts: AssembledParts): string {
  const lines: string[] = [];
  lines.push("// Generated by PrimBlocks — snap-together LSL for Second Life.");
  lines.push("// Paste into a New Script. default is required and must be first.");
  if (parts.notes?.length) {
    for (const n of parts.notes) lines.push(`// note: ${n}`);
  }
  lines.push("");

  const globals = parts.globals.map((g) => g.trim()).filter(Boolean);
  if (globals.length) {
    lines.push(...globals);
    lines.push("");
  }

  const functions = parts.functions.map((f) => f.trim()).filter(Boolean);
  if (functions.length) {
    lines.push(...functions);
    lines.push("");
  }

  const states: Record<string, string[]> = {};
  for (const [raw, events] of Object.entries(parts.states)) {
    const name = sanitizeStateName(raw);
    states[name] = [...(states[name] ?? []), ...events];
  }
  if (!states.default) states.default = [];

  lines.push(formatState("default", states.default, true));
  const rest = Object.keys(states)
    .filter((n) => n !== "default")
    .sort();
  for (const name of rest) {
    lines.push("");
    lines.push(formatState(name, states[name] ?? [], false));
  }

  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n")}\n`;
}

export const EMPTY_SCRIPT = assembleScript({
  globals: [],
  functions: [],
  states: { default: [] },
});
